const PRODUCTS = [
 {id:'xpr205m',brand:'Mettler Toledo',category:'Balanzas',sub:'Analítica',model:'XPR205/M',code:'30355413',capacity:'220 g',readability:'0,01 mg',image:'assets/catalogo/xpr205m.webp',description:'Balanza analítica XPR para aplicaciones de alta precisión, aseguramiento de calidad y flujos de trabajo regulados.',specs:{'Capacidad máxima':'220 g','Legibilidad':'0,01 mg','Repetibilidad, típica':'0,007 mg','Peso mínimo (U = 1 %, k = 2), típico':'1,4 mg','Peso mínimo (USP 0,1 %, típico)':'14 mg','Tiempo de estabilización':'2 s','Ajuste':'Interno (automático/FACT)','Dimensiones del plato de pesaje':'78 mm × 73 mm','Linealidad':'±0,1 mg','Línea de balanzas':'XPR','Tipo de balanza':'Balanza analítica','Familia':'Excellence'},source:'https://www.mt.com/mx/es/home/products/Laboratory_Weighing_Solutions/analytical-balances.html'},
 {id:'xpr105m',brand:'Mettler Toledo',category:'Balanzas',sub:'Analítica',model:'XPR105/M',code:'30355391',capacity:'120 g',readability:'0,01 mg',description:'Balanza analítica XPR con funciones de aseguramiento de calidad, compatibilidad con LabX y ajuste interno FACT.',specs:{'Capacidad máxima':'120 g','Legibilidad':'0,01 mg','Repetibilidad, típica':'0,007 mg','Peso mínimo (U = 1 %, k = 2), típico':'1,4 mg','Peso mínimo (USP 0,1 %, típico)':'14 mg','Tiempo de estabilización':'2 s','Ajuste':'Interno (automático/FACT)','Dimensiones del plato de pesaje':'78 mm × 73 mm','Linealidad':'±0,1 mg','Línea de balanzas':'XPR','Tipo de balanza':'Balanza analítica','Familia':'Excellence'},source:'https://www.mt.com/es/es/home/products/Laboratory_Weighing_Solutions/analytical-balances/XPR105-M.html'},
 {id:'xpr226drm',brand:'Mettler Toledo',category:'Balanzas',sub:'Analítica',model:'XPR226DR/M',code:'30594480',capacity:'220 g / 121 g',readability:'0,01 mg / 0,005 mg',description:'Balanza analítica XPR de doble rango con alta repetibilidad, puertas automáticas y soporte para flujos regulados.',specs:{'Capacidad máxima':'220 g / 121 g','Legibilidad':'0,01 mg / 0,005 mg','Repetibilidad, típica':'0,004 mg','Peso mínimo (U = 1 %, k = 2), típico':'0,8 mg','Peso mínimo (USP 0,1 %, típico)':'8 mg','Tiempo de estabilización':'2 s','Ajuste':'Interno (automático/FACT)','Dimensiones del plato de pesaje':'78 mm × 73 mm','Linealidad':'±0,1 mg','Línea de balanzas':'XPR','Tipo de balanza':'Balanza analítica','Familia':'Excellence'},source:'https://www.mt.com/es/es/home/products/Laboratory_Weighing_Solutions/analytical-balances/XPR226DR-M.html'},
 {id:'xpr226drqm',brand:'Mettler Toledo',category:'Balanzas',sub:'Automatizada',model:'XPR226DRQ/M',code:'30591937',capacity:'220 g / 121 g',readability:'0,01 mg / 0,005 mg',description:'Balanza XPR preparada para automatizar la dosificación de polvos y líquidos y reducir errores de usuario.',specs:{'N.º de material':'30591937','Línea de balanzas':'XPR','Tipo':'Balanza analítica automatizada','Aplicación':'Dosificación automática de polvos y líquidos','Familia':'Excellence'},source:'https://www.mt.com/es/es/home/products/Laboratory_Weighing_Solutions/analytical-balances/XPR226DRQ-M.html'},
 {id:'xpr3m',brand:'Mettler Toledo',category:'Balanzas',sub:'Microbalanza',model:'XPR3/M',code:'30875682',capacity:'3,1 g',readability:'1 µg',description:'Microbalanza XPR para muestras pequeñas y valiosas, con diseño compacto, transferencia directa de datos y soporte para entornos regulados.',specs:{'Capacidad máxima':'3,1 g','Legibilidad':'1 µg','Repetibilidad, típica':'0,5 µg','Peso mínimo (U = 1 %, k = 2), típico':'0,1 mg','Peso mínimo (USP 0,1 %, típico)':'1 mg','Ajuste':'Interno (automático/FACT)','Dimensiones':'179,5 mm × 123 mm × 356,5 mm','Diámetro del plato de pesaje':'27 mm','Línea de balanzas':'XPR','Tipo de balanza':'Microbalanza','Familia':'Excellence'},source:'https://www.mt.com/es/es/home/products/Laboratory_Weighing_Solutions/microbalances/XPR3-M.html'},
 {id:'xpr3',brand:'Mettler Toledo',category:'Balanzas',sub:'Microbalanza',model:'XPR3',code:'30875681',capacity:'3,1 g',readability:'1 µg',description:'Microbalanza XPR de 1 µg para pesaje de muestras de alto valor y trazabilidad avanzada.',specs:{'Capacidad máxima':'3,1 g','Legibilidad':'1 µg','Repetibilidad, típica':'0,5 µg','Peso mínimo (U = 1 %, k = 2), típico':'0,1 mg','Peso mínimo (USP 0,1 %, típico)':'1 mg','Ajuste':'Interno (automático/FACT)','Dimensiones':'179,5 mm × 123 mm × 356,5 mm','Diámetro del plato de pesaje':'27 mm','Línea de balanzas':'XPR','Tipo de balanza':'Microbalanza','Familia':'Excellence'},source:'https://www.mt.com/es/es/home/products/Laboratory_Weighing_Solutions/microbalances/XPR3.html'},
 {id:'xpr4002s',brand:'Mettler Toledo',category:'Balanzas',sub:'Precisión',model:'XPR4002S',code:'30317269',capacity:'4,1 kg',readability:'0,01 g',description:'Balanza de precisión XPR con SmartPan Pro para resultados estables y rápidos en laboratorio y producción.',specs:{'Capacidad máxima':'4,1 kg','Legibilidad':'0,01 g','N.º de material':'30317269','Línea de balanzas':'XPR','Tipo de balanza':'Balanza de precisión','Plato':'SmartPan Pro','Familia':'Excellence'},source:'https://www.mt.com/my/en/home/products/Laboratory_Weighing_Solutions/precision-balances/XPR4002S.html'}
];
const CATEGORIES=[
 {name:'Balanzas',icon:'⚖',desc:'Microbalanzas, balanzas analíticas y de precisión.',enabled:true},
 {name:'Analizadores de humedad',icon:'◫',desc:'Determinación rápida del contenido de humedad.',enabled:false},
 {name:'Titulación',icon:'⚗',desc:'Titulación potenciométrica y Karl Fischer.',enabled:false},
 {name:'pH y electrodos',icon:'⌁',desc:'Medición electroquímica y sensores.',enabled:false},
 {name:'Densidad',icon:'◉',desc:'Densímetros y soluciones para control de calidad.',enabled:false},
 {name:'Refractometría',icon:'◇',desc:'Refractómetros de laboratorio y proceso.',enabled:false},
 {name:'Análisis térmico',icon:'△',desc:'DSC, TGA y caracterización térmica.',enabled:false},
 {name:'Accesorios',icon:'＋',desc:'Accesorios, periféricos y consumibles.',enabled:false}
];
function qs(k){return new URLSearchParams(location.search).get(k)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function menu(){const b=document.getElementById('menuButton'),m=document.getElementById('menu');if(b&&m)b.onclick=()=>m.classList.toggle('open')}
function productCard(p){return `<article class="product-card" data-sub="${esc(p.sub)}" data-search="${esc((p.model+' '+p.code+' '+p.sub).toLowerCase())}"><div class="product-image ${p.image?'':'placeholder'}">${p.image?`<img src="${p.image}" alt="${esc(p.model)}">`:`<span>${esc(p.model)}<br><small>Imagen por incorporar</small></span>`}</div><div class="product-body"><div class="product-brand">${esc(p.brand)}</div><h3>${esc(p.model)}</h3><p class="product-meta">${esc(p.sub)} · ${esc(p.code)}</p><div class="product-spec">${esc(p.capacity)} · ${esc(p.readability)}</div><a class="product-link" href="producto.html?id=${encodeURIComponent(p.id)}">Ver ficha técnica →</a></div></article>`}
function renderBrands(){const el=document.getElementById('brands');if(!el)return;el.innerHTML=`<a class="brand-card" href="marca.html?marca=mettler-toledo"><div><div class="brand-wordmark">METTLER TOLEDO</div><h2>Mettler Toledo</h2><p>Equipos de laboratorio e instrumentación.</p></div><span>Ver categorías →</span></a><div class="brand-card"><div><div class="brand-wordmark">GIARDINO</div><h2>Giardino</h2><p>Catálogo en preparación.</p></div><span>Próximamente</span></div><div class="brand-card"><div><div class="brand-wordmark">HIXWER</div><h2>Hixwer</h2><p>Catálogo en preparación.</p></div><span>Próximamente</span></div>`}
function renderCategories(){const el=document.getElementById('categories');if(!el)return;el.innerHTML=CATEGORIES.map(c=>c.enabled?`<a class="category-card" href="catalogo.html?marca=mettler-toledo&categoria=${encodeURIComponent(c.name)}"><div><div class="category-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p></div><span>Ver equipos →</span></a>`:`<div class="category-card" style="opacity:.72"><div><div class="category-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p></div><span>En preparación</span></div>`).join('')}
function renderCatalog(){const el=document.getElementById('products');if(!el)return;const cat=qs('categoria')||'Balanzas';let data=PRODUCTS.filter(p=>p.category===cat);el.innerHTML=data.map(productCard).join('');const subs=['Todos',...new Set(data.map(p=>p.sub))];const chips=document.getElementById('chips');if(chips)chips.innerHTML=subs.map((s,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${esc(s)}">${esc(s)}</button>`).join('');const search=document.getElementById('search');function apply(){const active=document.querySelector('.chip.active')?.dataset.filter||'Todos',term=(search?.value||'').toLowerCase();document.querySelectorAll('.product-card').forEach(card=>{const okSub=active==='Todos'||card.dataset.sub===active;const okSearch=card.dataset.search.includes(term);card.style.display=okSub&&okSearch?'':'none'})}document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');apply()});if(search)search.oninput=apply}
function renderProduct(){const el=document.getElementById('productDetail');if(!el)return;const p=PRODUCTS.find(x=>x.id===qs('id'));if(!p){el.innerHTML='<div class="empty">Producto no encontrado.</div>';return}document.title=`${p.model} | Exacta Perú`;const rows=Object.entries(p.specs).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('');const msg=encodeURIComponent(`Buenos días. Deseo información y cotización de ${p.brand} ${p.model} (${p.code}).`);el.innerHTML=`<div class="crumbs"><a href="marcas.html">Marcas</a> › <a href="marca.html?marca=mettler-toledo">Mettler Toledo</a> › <a href="catalogo.html?marca=mettler-toledo&categoria=Balanzas">Balanzas</a> › ${esc(p.model)}</div><section class="detail"><div class="detail-media ${p.image?'':'placeholder'}">${p.image?`<img src="${p.image}" alt="${esc(p.model)}">`:`<div style="text-align:center;color:#8b98a8"><strong>${esc(p.model)}</strong><br>Imagen del producto por incorporar</div>`}</div><div><div class="product-brand">${esc(p.brand)}</div><h1>Balanza ${esc(p.model)} Mettler Toledo</h1><p class="code">Código: ${esc(p.model)} | ${esc(p.code)} · Categoría: ${esc(p.category)}</p><span class="badge">Marca disponible · suministro sujeto a confirmación</span><p class="description">${esc(p.description)}</p><div class="actions"><a class="btn btn-primary" href="mailto:contacto@exactaperu.com?subject=${encodeURIComponent('Cotización '+p.model)}">Solicitar cotización</a><a class="btn btn-whatsapp" target="_blank" href="https://wa.me/51932610623?text=${msg}">WhatsApp</a><a class="btn btn-outline" target="_blank" rel="noopener" href="${p.source}">Ver referencia del fabricante</a></div><div class="spec-wrap"><h2>Especificaciones técnicas</h2><table class="spec-table">${rows}</table><p class="source-note">Información técnica de referencia. Confirme configuración, disponibilidad y versión aplicable al solicitar una cotización.</p></div></div></section>`}
document.addEventListener('DOMContentLoaded',()=>{menu();renderBrands();renderCategories();renderCatalog();renderProduct()});
