let PRODUCTS=[];
const CATEGORIES=[
 {name:'Balanzas',icon:'⚖',desc:'Microbalanzas, balanzas analíticas y de precisión.',enabled:true},
 {name:'Analizadores de humedad',icon:'◫',desc:'HX204, HS153, HC103, HE73 y HE53.',enabled:true},
 {name:'Titulación',icon:'⚗',desc:'Valoradores Excellence, potenciometría y Karl Fischer.',enabled:true},
 {name:'pH y electrodos',icon:'⌁',desc:'NineFocus, medición electroquímica y sensores InLab.',enabled:true},
 {name:'Densidad',icon:'◉',desc:'Densímetros Excellence y soluciones multiparámetro.',enabled:true},
 {name:'Refractometría',icon:'◇',desc:'Refractómetros Excellence para nD, Brix y más.',enabled:true},
 {name:'Análisis térmico',icon:'△',desc:'TGA, DSC y caracterización térmica.',enabled:true},
 {name:'Punto de fusión y goteo',icon:'♨',desc:'Sistemas MP y DP para punto de fusión, goteo, reblandecimiento y otros valores térmicos.',enabled:true},
 {name:'Accesorios',icon:'＋',desc:'Accesorios, automatización, periféricos y consumibles.',enabled:true}
];
function qs(k){return new URLSearchParams(location.search).get(k)}
function esc(s){return String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]))}
function menu(){const b=document.getElementById('menuButton'),m=document.getElementById('menu');if(b&&m)b.onclick=()=>m.classList.toggle('open')}
function kind(p){if(p.category==='Balanzas')return 'Balanza';if(p.category==='Analizadores de humedad')return 'Analizador de humedad';if(p.category==='Análisis térmico')return 'Sistema';if(p.category==='Titulación')return 'Valorador';if(p.category==='pH y electrodos')return 'Medidor';if(p.category==='Densidad')return 'Densímetro';if(p.category==='Refractometría')return 'Refractómetro';if(p.category==='Punto de fusión y goteo')return 'Sistema de valores térmicos';return 'Equipo'}
function iconClass(p){return p.category==='Analizadores de humedad'?'moisture':p.category==='Análisis térmico'?'thermal':'balance'}
function placeholder(p,detail=false){return `<div class="equipment-placeholder ${detail?'detail-placeholder':''}"><div class="generic-icon ${iconClass(p)}"><span></span></div><strong>${esc(p.model)}</strong><small>${detail?'Fotografía del producto en preparación':'Fotografía en preparación'}</small></div>`}
function productCard(p){return `<article class="product-card" data-sub="${esc(p.sub)}" data-search="${esc((p.model+' '+p.code+' '+p.sub).toLowerCase())}"><div class="product-image ${p.image?'':'placeholder'}">${p.image?`<img src="${p.image}" alt="${esc(p.model)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.closest('.product-image')?.classList.add('image-error');this.style.display='none'">`:placeholder(p)}</div><div class="product-body"><div class="product-brand">${esc(p.brand)}</div><h3>${esc(p.model)}</h3><p class="product-meta">${esc(p.sub)}${p.code?' · '+esc(p.code):''}</p><div class="product-spec">${esc(p.capacity)} · ${esc(p.readability)}</div><a class="product-link" href="producto.html?id=${encodeURIComponent(p.id)}">Ver ficha técnica →</a></div></article>`}
function renderBrands(){const el=document.getElementById('brands');if(!el)return;el.innerHTML=`<a class="brand-card" href="marca.html?marca=mettler-toledo"><div><div class="brand-wordmark">METTLER TOLEDO</div><h2>Mettler Toledo</h2><p>Equipos de laboratorio e instrumentación.</p></div><span>Ver categorías →</span></a><div class="brand-card"><div><div class="brand-wordmark">GIARDINO</div><h2>Giardino</h2><p>Catálogo en preparación.</p></div><span>Próximamente</span></div><div class="brand-card"><div><div class="brand-wordmark">HIXWER</div><h2>Hixwer</h2><p>Catálogo en preparación.</p></div><span>Próximamente</span></div>`}
function renderCategories(){const el=document.getElementById('categories');if(!el)return;el.innerHTML=CATEGORIES.map(c=>c.enabled?`<a class="category-card" href="catalogo.html?marca=mettler-toledo&categoria=${encodeURIComponent(c.name)}"><div><div class="category-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p></div><span>Ver equipos →</span></a>`:`<div class="category-card" style="opacity:.72"><div><div class="category-icon">${c.icon}</div><h3>${c.name}</h3><p>${c.desc}</p></div><span>En preparación</span></div>`).join('')}
function renderCatalog(){const el=document.getElementById('products');if(!el)return;const cat=qs('categoria')||'Balanzas';const data=PRODUCTS.filter(p=>p.category===cat);const count=document.getElementById('productCount');if(count)count.textContent=`${data.length} equipos cargados`;const title=document.querySelector('.page-hero h1');if(title)title.textContent=cat;const crumb=document.querySelector('.page-hero .crumbs');if(crumb)crumb.innerHTML=`<a href="marcas.html">Marcas</a> › <a href="marca.html?marca=mettler-toledo">Mettler Toledo</a> › ${esc(cat)}`;const intro=document.querySelector('.page-hero p');if(intro)intro.textContent=cat==='Balanzas'?'Modelos de microbalanzas, balanzas analíticas y de precisión con ficha técnica individual.':cat==='Analizadores de humedad'?'Equipos para determinación rápida de humedad, desde tareas rutinarias hasta aplicaciones reguladas.':cat==='Análisis térmico'?'Instrumentación para caracterización térmica de materiales.':'Equipos disponibles con ficha técnica individual.';el.innerHTML=data.map(productCard).join('')||'<div class="empty">Catálogo en preparación.</div>';const subs=['Todos',...new Set(data.map(p=>p.sub))];const chips=document.getElementById('chips');if(chips)chips.innerHTML=subs.map((s,i)=>`<button class="chip ${i===0?'active':''}" data-filter="${esc(s)}">${esc(s)}</button>`).join('');const search=document.getElementById('search');function apply(){const active=document.querySelector('.chip.active')?.dataset.filter||'Todos',term=(search?.value||'').toLowerCase();document.querySelectorAll('.product-card').forEach(card=>{card.style.display=(active==='Todos'||card.dataset.sub===active)&&card.dataset.search.includes(term)?'':'none'})}document.querySelectorAll('.chip').forEach(c=>c.onclick=()=>{document.querySelectorAll('.chip').forEach(x=>x.classList.remove('active'));c.classList.add('active');apply()});if(search)search.oninput=apply}
function renderProduct(){const el=document.getElementById('productDetail');if(!el)return;const p=PRODUCTS.find(x=>x.id===qs('id'));if(!p){el.innerHTML='<div class="empty">Producto no encontrado.</div>';return}document.title=`${p.model} | Exacta Perú`;const rows=Object.entries(p.specs).map(([k,v])=>`<tr><td>${esc(k)}</td><td>${esc(v)}</td></tr>`).join('');const msg=encodeURIComponent(`Buenos días. Deseo información y cotización de ${p.brand} ${p.model}${p.code?' ('+p.code+')':''}.`);el.innerHTML=`<div class="crumbs"><a href="marcas.html">Marcas</a> › <a href="marca.html?marca=mettler-toledo">Mettler Toledo</a> › <a href="catalogo.html?marca=mettler-toledo&categoria=${encodeURIComponent(p.category)}">${esc(p.category)}</a> › ${esc(p.model)}</div><section class="detail"><div class="detail-media ${p.image?'':'placeholder'}">${p.image?`<img src="${p.image}" alt="${esc(p.model)}" loading="lazy" referrerpolicy="no-referrer" onerror="this.closest('.product-image')?.classList.add('image-error');this.style.display='none'">`:placeholder(p,true)}</div><div><div class="product-brand">${esc(p.brand)}</div><h1>${kind(p)} ${esc(p.model)} Mettler Toledo</h1><p class="code">${p.code?'Código: '+esc(p.code)+' · ':''}Categoría: ${esc(p.category)}</p><span class="badge">Marca disponible · suministro sujeto a confirmación</span><p class="description">${esc(p.description)}</p><div class="actions"><a class="btn btn-primary" href="mailto:contacto@exactaperu.com?subject=${encodeURIComponent('Cotización '+p.model)}">Solicitar cotización</a><a class="btn btn-whatsapp" target="_blank" href="https://wa.me/51932610623?text=${msg}">WhatsApp</a><a class="btn btn-outline" target="_blank" rel="noopener" href="${p.source}">Ver referencia del fabricante</a></div><div class="spec-wrap"><h2>Especificaciones técnicas</h2><table class="spec-table">${rows}</table></div>${p.highlights?.length?`<section class="info-block"><h2>Características principales</h2><ul class="feature-list">${p.highlights.map(v=>`<li>${esc(v)}</li>`).join('')}</ul></section>`:''}${p.applications?.length?`<section class="info-block"><h2>Aplicaciones</h2><div class="application-tags">${p.applications.map(v=>`<span>${esc(v)}</span>`).join('')}</div></section>`:''}<div class="technical-note"><strong>Nota técnica</strong><p>Las prestaciones corresponden a información de referencia para el modelo indicado. La configuración, versión metrológica, accesorios, software y disponibilidad deben confirmarse antes de emitir una oferta.</p></div><p class="source-note"><a target="_blank" rel="noopener" href="${p.source}">Consultar fuente técnica del fabricante →</a></p></div></section>`}
async function init(){menu();try{const r=await fetch('productos.json?v=9');if(!r.ok)throw new Error();PRODUCTS=await r.json()}catch(e){console.error('No se pudo cargar productos.json')}renderBrands();renderCategories();renderCatalog();renderProduct()}
document.addEventListener('DOMContentLoaded',init);
