"""Reviewed specifications from manufacturer pages, checked 2026-10-07.

Keys are supplier record IDs used to locate existing files, never product SKUs.
Voltage-specific specifications are attributed to the corresponding variant.
"""

FACTS = {
    3405: [('Referencia del repuesto', 'HI764080A/P'), ('Compatibilidad', 'Sonda polarográfica digital de oxígeno disuelto HI764080 para medidores edge'), ('Presentación', '2 piezas'), ('Cuerpo del tapón', 'ABS'), ('Membrana permeable al oxígeno', 'PTFE'), ('Diseño', 'Tapón roscado rellenable con electrolito')],
    5453: [('Modelo', 'V-100; referencia anterior Stuart SA7'), ('Velocidad', '2500 rpm, fija'), ('Activación', 'Por presión sobre la copa; se detiene al retirar el recipiente'), ('Diámetro orbital', '4,2 mm'), ('Cabezal incluido', 'Copa de goma'), ('Carcasa', 'Fundición a presión'), ('Alimentación', '90–240 V CA, 50/60 Hz'), ('Protección', 'IP31')],
    5496: [('Serie', 'WBU-250'), ('Tipo', 'Baño de calibración para uso con circulador externo'), ('Capacidades nominales', '5, 7 y 12 L, según modelo'), ('Estabilidad térmica', 'Hasta ±0,005 °C, dependiendo del controlador utilizado'), ('Refrigeración', 'Serpentín para agua fría; enfriador de flujo adicional para alcanzar −35 °C'), ('Aislamiento', 'Laterales y base aislados'), ('Requisito de operación', 'Circulador de inmersión compatible, vendido por separado'), ('Incluye', 'Tapa, drenaje, asas y serpentín de refrigeración')],
    5500: [('Tipo', 'Limpiador ultrasónico digital con calefacción y doble frecuencia'), ('Frecuencias seleccionables', '37 o 80 kHz'), ('Calefacción', '30–80 °C; ajuste en pasos de 5 °C'), ('Temporizador', '1–30 minutos o funcionamiento continuo'), ('Modos', 'Normal, pulso, barrido, desgasificación, pausa e inicio automático'), ('Pulso', 'Incremento del 20 % de potencia ultrasónica'), ('Protección', 'Apagado tras 12 horas continuas o temperatura de baño superior a 90 °C'), ('Alimentación para Perú', 'Confirmar configuración de 220–240 V antes de cotizar')],
    5504: [('Serie', 'WBU-200'), ('Tipo', 'Baño sin calefacción integrada'), ('Interior', 'Acero inoxidable sin costuras'), ('Carcasa exterior', 'Acero esmaltado resistente a salpicaduras'), ('Circulador compatible', 'IC-300; vendido por separado'), ('Incluye', 'Placa puente para fijar el circulador y asas de transporte'), ('Capacidad', 'Depende del tamaño de tanque seleccionado')],
    5522: [('Serie', 'IC-400'), ('Tipo', 'Circulador de inmersión con calentador y bomba integrados'), ('Depósito compatible', 'Hasta 28 L'), ('Pantalla', 'Digital retroiluminada; temperatura real y programada'), ('Caudal', 'Ajustable mediante control deslizante'), ('Ajustes', 'Temperatura, unidades °C/°F y compensación de calibración'), ('Montaje', 'Abrazadera ajustable para paredes planas o curvas'), ('Protección física', 'Carcasa alrededor de bomba y resistencia')],
    5526: [('Serie', 'IP-400'), ('Tipo', 'Enfriador con sonda de inmersión'), ('Temperatura mínima de la familia', 'Hasta −100 °C, según modelo y condiciones de carga'), ('Sonda', 'Acero inoxidable con manguera flexible'), ('Operación', 'Refrigeración a máxima capacidad'), ('Control de temperatura', 'Sin punto de ajuste de baja temperatura regulable'), ('Aplicaciones', 'Enfriamiento de líquidos, reacciones exotérmicas y captura de vapores')],
    5554: [('Serie', 'FSB-200 de precisión'), ('Rango de temperatura', '50–700 °C'), ('Medio', 'Óxido de aluminio fluidizado; solicitar por separado'), ('Control', 'PID con termopar tipo K'), ('Estabilidad a corto plazo', '±0,2 °C a 50 °C; ±0,3 °C a 600 °C'), ('Estabilidad a largo plazo', '±0,5 °C a 50 y 600 °C'), ('Control de aire', 'Manual o automático; interfaz RS-232 en la variante automática'), ('Alimentación de variantes publicadas', '230 V CA, 50/60 Hz'), ('Aplicación', 'Calibración de sensores y ensayos térmicos')],
    5558: [('Serie', 'SC-200'), ('Tipo', 'Concentrador de muestras por evaporación con gas inerte'), ('Versiones', 'Para tubos o placas de 96 pocillos'), ('Recorrido vertical máximo', '32 cm'), ('Consumo máximo de gas', '15 L/min'), ('Posición de agujas', 'Ajustable mediante matriz de silicona'), ('Se venden por separado', 'Agujas, bloques y calentador'), ('Opción para muestras corrosivas', 'Agujas con recubrimiento de PTFE')],
    5576: [('Tipo', 'Bomba de vacío neumática por efecto Venturi'), ('Alimentación', 'Aire comprimido; sin electricidad ni lubricación'), ('Diseño', 'Sin piezas móviles'), ('Vacío máximo', 'Depende del modelo; confirmar referencia y condiciones de alimentación'), ('Modelo con manómetro', '78165-20'), ('Filtro recomendado', 'Aguas arriba; tamaño de poro de 50 µm o menor')],
    5582: [('Serie', 'VPS-200 Air Admiral'), ('Tipo', 'Bomba portátil de vacío/presión'), ('Carcasa', 'Plástico con asa integrada'), ('Configuración de 230 V', 'Referencia 79202-05'), ('Caudal libre de la referencia 79202-05', '8,8 L/min'), ('Presión máxima de la referencia 79202-05', '2,27 bar'), ('Vacío máximo de la referencia 79202-05', '21,3 inHg'), ('Restricciones', 'No bombear líquidos; evitar vapores orgánicos, ácidos y básicos')],
    5620: [('Serie', 'WS-200 tipo gabinete'), ('Construcción', 'Vidrio borosilicato y calentadores revestidos de sílice'), ('Configuraciones', 'Destilación simple o doble según modelo'), ('Control del depósito', 'Sensor de nivel que detiene el equipo al llenarse'), ('Limpieza', 'Descalcificación sin desmontar el vidrio'), ('Drenaje', 'Llave de paso de PTFE'), ('Alimentación', 'Seleccionar variante compatible con 220–240 V')],
    5622: [('Serie', 'WS-200'), ('Configuración de referencia', 'WS-200-4; referencia 99295-00'), ('Producción de WS-200-4', '4 L/h'), ('Alimentación de WS-200-4', '240 V CA'), ('Construcción', 'Vidrio con calentadores revestidos de sílice'), ('Protección', 'Dos termostatos independientes; parada por depósito lleno'), ('Montaje', 'Banco o pared'), ('Conexiones', 'Roscadas para cambio de mangueras y limpieza')],
    5636: [('Serie', 'SW-200'), ('Tipo', 'Calentador y secador de portaobjetos'), ('Capacidad', 'Hasta 50 portaobjetos de 76 × 25 mm'), ('Temperatura', 'Ambiente hasta 100 °C'), ('Control', 'Regulador de energía con dial e indicadores de alimentación y calentamiento'), ('Dimensiones', '39 × 9,5 × 18 cm (ancho × alto × fondo)'), ('Incluye', 'Barras de soporte para distintas orientaciones de secado'), ('Configuración para Perú', 'Referencia 48573-06; 230 V CA, 50/60 Hz')],
    5686: [('Tipo', 'Conducto de luz de fibra óptica autoportante'), ('Construcción', 'Fibras de vidrio recubiertas con espiral de acero'), ('Posicionamiento', 'Brazo flexible; no requiere soporte adicional'), ('Conexión', 'Directa al iluminador compatible'), ('Configuraciones', 'Uno o dos brazos según referencia'), ('Se vende por separado', 'Base de iluminación 41720-40')],
    5692: [('Tipo', 'Iluminador LED de fibra óptica'), ('Intensidad', 'Ajustable del 10 al 100 %'), ('Refrigeración', 'Ventilador integrado'), ('Diseño', 'Carcasa apilable y asa integrada'), ('Configuración de referencia', 'Doble cuello de cisne; referencia 41723-12'), ('Alimentación de 41723-12', '100–240 V CA, 50/60 Hz; cable europeo de 230 V'), ('Salida luminosa de 41723-12', '2000 lúmenes; 5000 K'), ('Vida nominal del LED de 41723-12', '40000 horas')],
    5694: [('Tipo', 'Transiluminador ultravioleta'), ('Aplicación', 'Visualización y fotografía de fluorescencia'), ('Iluminación', 'Tubos UV de alta intensidad; banda según modelo'), ('Cubierta', 'Bloqueo UV con inclinación ajustable'), ('Marco', 'Acero inoxidable'), ('Refrigeración', 'Ventilador para reducir la temperatura de la superficie'), ('Variantes', 'Intensidad doble y opciones de banda media o larga según referencia')],
    5706: [('Serie', 'INC-200 para microplacas'), ('Configuración de referencia', 'INC-200D-M; referencia 39065-15'), ('Capacidad de INC-200D-M', '20 L'), ('Temperatura máxima de INC-200D-M', '80 °C'), ('Resolución de temperatura', '0,1 °C'), ('Alimentación de 39065-15', '230 V CA, 50 Hz; 350 W'), ('Control', 'Microprocesador y circulación forzada de aire; pantalla LED'), ('Incluye', '4 estantes y bandeja de agua de acero inoxidable'), ('Protección', 'Sistema contra sobrecalentamiento')],
    5720: [('Serie', 'INC-200 transparente'), ('Material', 'Acrílico transparente'), ('Capacidad nominal', '60 L'), ('Temperatura', 'Ambiente +5 °C hasta 60 °C'), ('Fluctuación a 37 °C', '±0,1 °C'), ('Control', 'Analógico o digital según modelo; preajuste de 37 °C'), ('Puertos laterales', 'Dos de 10 mm en cada panel para gases o cables'), ('Base', 'No incluida; placa opcional 01110-97'), ('Versiones de 230 V', '01110-02 analógica; 01110-08 digital')],
    5728: [('Serie', 'HM-200 para matraces y embudos'), ('Geometría', 'Cavidad cónica con abertura inferior para embudos de 60°'), ('Temperatura máxima del elemento', '450 °C; no equivale a la temperatura de la muestra'), ('Carcasa', 'Polipropileno'), ('Aislamiento', 'Fibra cerámica'), ('Control', 'Regulador de potencia integrado; dial de 1 a 10'), ('Variantes', 'HM-200-V con malla de protección; HM-200-SP con revestimiento de acero inoxidable'), ('Alimentación', 'Seleccionar variante de 230 V')],
    5746: [('Serie', 'FF-200 industrial'), ('Configuración de referencia', 'FF-200D-I; referencia 83055-05'), ('Método', 'Fotometría de llama de baja temperatura; canal único'), ('Filtros incluidos', 'Sodio, potasio, litio, calcio y bario'), ('Rango publicado', '0–199,9 ppm'), ('Reproducibilidad', 'Mejor que 1 % CV'), ('Estabilización de lectura', 'Aproximadamente 8 segundos'), ('Consumo de muestra', '2–6 mL/min'), ('Suministro de aire', '6 L/min a 14 psi; sin aceite ni humedad'), ('Alimentación de 83055-05', '230 V CA, 50/60 Hz'), ('Protección', 'Corte automático de gas al extinguirse la llama')],
    5748: [('Serie', 'FJT-200'), ('Tipo', 'Equipo de prueba de jarras para floculación'), ('Configuraciones', '2 o 6 posiciones'), ('Recipientes compatibles', 'Vasos de 1 L, no incluidos'), ('Paletas', 'Acero inoxidable'), ('Control', 'Retroalimentación electrónica y pantalla digital de velocidad'), ('Programas', 'Dos ajustes de velocidad y tiempo almacenables'), ('Configuración de 6 posiciones', 'FJT-200D-6; referencia 99551-05; 230 V CA, 50 Hz'), ('Velocidad de FJT-200D-6', '25–250 rpm'), ('Temporizador de FJT-200D-6', '0–99 minutos')],
    5756: [('Tipo', 'Caudalímetro de área variable'), ('Escala', 'Optigrad de 150 mm'), ('Fluidos', 'Aire o agua; tubo según caudal y condiciones de operación'), ('Racores', 'Aluminio'), ('Válvula', 'Cartucho integrado de alta resolución'), ('Conexión', '1/8 pulgadas NPT hembra'), ('Montaje', 'Panel con tuercas hexagonales'), ('Lectura', 'Protector frontal con aumento y adaptador antirrotación')],
    5762: [('Tipo', 'Medidor ambiental 4 en 1'), ('Parámetros', 'Velocidad del aire, temperatura, humedad relativa e iluminancia'), ('Humedad relativa', '10–95 % HR'), ('Iluminancia', '0–20000 lux'), ('Temperatura ambiente', '0–50 °C'), ('Sonda externa', 'Termopar tipo K con miniconector'), ('Funciones', 'HOLD y MIN/MAX; °C/°F seleccionable'), ('Incluye', 'Sonda tipo K de 1,2 m, correa y batería de 9 V')],
    5780: [('Serie', 'PCR-300 Alpha'), ('Tipo', 'Termociclador para PCR'), ('Configuraciones', '1, 2 o 4 bloques según modelo'), ('Formatos de bloque', '96 o 384 pocillos; formatos mixtos según configuración'), ('Control de bloques', 'Independiente'), ('Interfaz', 'Pantalla táctil y asistente de programación'), ('Tapa', 'Calefactada y ajustable'), ('Refrigeración', 'Activa de la muestra'), ('Registro', 'Aproximadamente 1000 informes almacenables')],
    5804: [('Serie', 'PB-100'), ('Tipo', 'Balanza portátil de carga superior'), ('PB-100-100', '100 g × 0,001 g; referencia de 220 V: 20000-33'), ('PB-100-200', '200 g × 0,01 g; referencia de 220 V: 20000-35'), ('PB-100-300', '300 g × 0,1 g; referencia de 220 V: 20000-49'), ('PB-100-400', '400 g × 0,01 g; referencia de 220 V: 20000-37'), ('PB-100-800', '800 g × 0,01 g; referencia de 220 V: 20000-39'), ('PB-100-500', '500 g × 0,1 g; referencia de 220 V: 20000-52'), ('PB-100-1200', '1200 g × 0,1 g; referencia de 220 V: 20000-41'), ('PB-100-2000', '2000 g × 0,1 g; referencia de 220 V: 20000-43'), ('PB-100-4000', '4000 g × 0,1 g; referencia de 220 V: 20000-45'), ('Conectividad', 'RS-232 para impresora u ordenador'), ('Calibración', 'Externa'), ('Alimentación portátil', 'Batería recargable; adaptador según configuración')],
}

for record, fluid, fitting, valve in [(5754, 'Aire', 'Latón', True), (5760, 'Aire', 'Acero inoxidable', True), (5764, 'Aire', 'Acero inoxidable', False), (5766, 'Agua', 'Acero inoxidable', True), (5770, 'Agua', 'Acero inoxidable', False)]:
    FACTS[record] = [('Tipo', 'Caudalímetro de área variable'), ('Fluido', fluid), ('Cuerpo', 'Acrílico transparente'), ('Racores', fitting), ('Válvula', 'Integrada' if valve else 'Sin válvula'), ('Exactitud', '±5 % del fondo de escala'), ('Temperatura máxima de operación', '65 °C'), ('Presión máxima', '100 psi (6,9 bar)'), ('Montaje', 'Panel o en línea según configuración'), ('Rango de caudal', 'Seleccionar referencia según caudal requerido')]

SOURCES = {
    3405: 'https://hannainst.com/hi764080a-p-spare-dissolved-oxygen-screw-cap-membranes.html',
    5453: 'https://pim-resources.coleparmer.com/data-sheet/04729-01-v-100-vortex-mixer-ds.pdf',
    5496: 'https://www.coleparmer.com/p/cole-parmer-wbu-250-series-water-baths/52293',
    5500: 'https://www.coleparmer.com/p/cole-parmer-advanced-high-power-heated-digital-ultrasonic-cleaners/81887',
    5504: 'https://www.coleparmer.com/p/cole-parmer-wbu-200-series-unheated-water-baths/66806',
    5522: 'https://www.coleparmer.com/p/cole-parmer-ic-400-series-standard-immersion-circulator/80201',
    5526: 'https://www.coleparmer.com/p/cole-parmers-ip-400-series-low-temperature-immersion-probe-chillers/80215',
    5554: 'https://www.coleparmer.com/i/cole-parmer-fsb-200-p-precision-fluidized-sand-bath-230-v-50-60-hz/1218403',
    5558: 'https://www.coleparmer.com/p/cole-parmer-sc-200-series-sample-concentrators/66709',
    5576: 'https://www.coleparmer.com/p/cole-parmer-air-powered-venturi-vacuum-pumps/6906',
    5582: 'https://www.coleparmer.com/i/cole-parmer-vps-200-air-admiral-vacuum-pressure-pump-0-31-cfm-230-vac/7920205',
    5620: 'https://www.coleparmer.com/p/cole-parmer-ws-200-series-cabinet-style-water-stills/66749',
    5622: 'https://www.coleparmer.com/i/cole-parmer-ws-200-4-water-still-240-vac/9929500',
    5636: 'https://pim-resources.coleparmer.com/data-sheet/48573-01-06-slide-drying-bench-sell-sheet.pdf',
    5686: 'https://www.coleparmer.com/i/cole-parmer-self-supportng-single-arm-gooseneck-fiber-optic-light-pipe-20-50-8-cm/4172075',
    5692: 'https://www.coleparmer.com/i/cole-parmer-led-fiber-optic-illuminator-dual-gooseneck-light-pipe-230-vac/4172312',
    5694: 'https://www.coleparmer.com/p/cole-parmer-high-performance-uv-transilluminators/54437',
    5706: 'https://www.coleparmer.com/i/cole-parmer-inc-200d-m-microplate-incubator-20-l-230-vac/3906515',
    5720: 'https://pim-resources.coleparmer.com/data-sheet/01110-00-02-04-08-incubator-inc-200-inc-200d-data-sheet.pdf',
    5728: 'https://www.coleparmer.com/p/cole-parmer-hm-200-series-flask-funnel-heating-mantles/2143',
    5746: 'https://www.coleparmer.com/i/cole-parmer-ff-200d-i-general-purpose-flame-photometer-230-vac-50-60-hz/8305505',
    5748: 'https://www.coleparmer.com/i/cole-parmer-fjt-200d-6-flocculation-jar-tester-6-place-230-vac-50-hz/9955105',
    5756: 'https://www.coleparmer.com/p/cole-parmer-variable-area-flowmeters-150-mm-aluminum-mounting-fitting-cartridge-valve/89967',
    5762: 'https://www.coleparmer.com/i/cole-parmer-environmental-meter-wind-speed-humidity-temperature-and-light-meter/9876687',
    5780: 'https://www.coleparmer.com/p/cole-parmer-pcr-300-alpha-cyclers/66757',
    5804: 'https://pim-resources.coleparmer.com/data-sheet/20000-32-52-pb-100-datasheet.pdf',
}
for record in (5754, 5760, 5764, 5766, 5770):
    SOURCES[record] = 'https://pim-resources.coleparmer.com/data-sheet/variable-area-acrylic-flowmeters-ss-8-5x11-final-rev.pdf'

assert FACTS.keys() == SOURCES.keys()
